name: Test Post CI

on:
  workflow_dispatch:

jobs:
  test-post-toot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Installing dependencises using poetry
        run: poetry install --no-dev
      - name: post toot
        env:
          USER_CRED: ${{secrets.TEST_USER_CRED}}
        run: poetry run python gensokyo_night/gensokyo_night.py